03:56:12 [Skill] INFO  Skill:138 - Connecting to Furhat server on 192.168.2.3:1932
03:56:13 [OpenaichatSkill] INFO  OpenaichatSkill:165 - Starting skill
03:56:21 [ErrorLoggingThread] ERROR OpenaichatSkill:458 - Exception in thread "OpenaichatSkill" java.lang.ExceptionInInitializerError
	at furhatos.app.openaichat.flow.GreetingKt$Greeting$1$1.invoke(greeting.kt:14)
	at furhatos.app.openaichat.flow.GreetingKt$Greeting$1$1.invoke(greeting.kt)
	at furhatos.flow.kotlin.StateRunner.runEntryTrigger(StateRunner.kt:180)
	at furhatos.flow.kotlin.StateRunner.run(StateRunner.kt:65)
	at furhatos.flow.kotlin.Flow.tailRecRun(Flow.kt:147)
	at furhatos.flow.kotlin.Flow.run(Flow.kt:111)
	at furhatos.app.openaichat.OpenaichatSkill.start(main.kt:13)
	at furhatos.skills.Skill.initializeSkill(Skill.java:168)
	at furhatos.skills.Skill.lambda$startSkill$2(Skill.java:226)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.net.ConnectException: Connection refused: connect
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:579)
	at java.base/sun.nio.ch.Net.connect(Net.java:568)
	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:588)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
	at java.base/java.net.Socket.connect(Socket.java:633)
	at java.base/java.net.Socket.connect(Socket.java:583)
	at java.base/java.net.Socket.<init>(Socket.java:507)
	at java.base/java.net.Socket.<init>(Socket.java:287)
	at furhatos.app.openaichat.flow.chatbot.ChatKt.<clinit>(chat.kt:19)
	... 10 more

